hw07/lib/hw07_web/router.ex
defmodule Hw07Web.Router do
  use Hw07Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw07Web.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug Hw07Web.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hw07Web do
    pipe_through :browser

    get "/", TaskController, :index
    get "/task_report", TaskController, :task_report
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", Hw07Web do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw07Web do
  #   pipe_through :api
  # end
end

hw07/lib/hw07/tasks/task.ex
defmodule Hw07.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset


  schema "tasks" do
    field :completed, :boolean, default: false
    field :desc, :string
    field :time_spent, :integer
    field :title, :string
    belongs_to :user, Hw07.Users.User
    has_many :time_blocks, Hw07.TimeBlocks.TimeBlock

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:title, :desc, :completed, :time_spent, :user_id])
    |> validate_required([:title, :desc, :completed, :time_spent, :user_id])
  end
end

hw07/lib/hw07/tasks/tasks.ex
defmodule Hw07.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias Hw07.Repo

  alias Hw07.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all from t in Task, preload: [:user]
  end

  def task_report(user) do
    Repo.all from t in Task,
       left_join: u in assoc(t, :user),
       where: u.manager_id == ^user.id,
       preload: [:user]
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id) do
    Repo.one! from t in Task,
              where: t.id == ^id,
              preload: [:time_blocks]
  end

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
end

hw07/lib/hw07_web/controllers/task_controller.ex
defmodule Hw07Web.TaskController do
  use Hw07Web, :controller

  alias Hw07.Tasks
  alias Hw07.Users
  alias Hw07.TimeBlocks
  alias Hw07.Tasks.Task
  alias Hw07.TimeBlocks.TimeBlock

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    if (!conn.assigns[:current_user]) do
      conn
      |> put_flash(:error, "You need to be logged in to make a task")
      |> redirect(to: Routes.user_path(conn, :index))
      |> halt
    end

    users = Users.list_underlings(conn.assigns[:current_user])

    if (Enum.count(users) < 1) do
      conn
      |> put_flash(:error, "You need to have underlings to assign a task")
      |> redirect(to: Routes.user_path(conn, :index))
      |> halt
    end

    {_, default_user_id } = List.first(users)
    changeset = Tasks.change_task(%Task{
      completed: false,
      time_spent: 0,
      user_id: default_user_id,
    })
    render(conn, "new.html", changeset: changeset, users: users)
  end

  def create(conn, %{"task" => task_params}) do
    case Tasks.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        users = Users.list_underlings(conn.assigns[:current_user])
        render(conn, "new.html", changeset: changeset, users: users)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    changeset = TimeBlocks.change_time_block(%TimeBlock{
      task_id: task.id,
    })
    render(conn, "show.html", task: task, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    if (!conn.assigns[:current_user]) do
      conn
      |> put_flash(:error, "You need to be logged in to edit a task")
      |> redirect(to: Routes.user_path(conn, :index))
      |> halt
    end

    task = Tasks.get_task!(id)
    changeset = Tasks.change_task(task)
    users = Users.list_underlings(conn.assigns[:current_user])
    render(conn, "edit.html", task: task, changeset: changeset, users: users)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)

    case Tasks.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        users = Users.list_underlings(conn.assigns[:current_user])
        render(conn, "edit.html", task: task, changeset: changeset, users: users)
    end
  end

  def delete(conn, %{"id" => id}) do
    if (!conn.assigns[:current_user]) do
      conn
      |> put_flash(:error, "You need to be logged in to delete a task")
      |> redirect(to: Routes.user_path(conn, :index))
      |> halt
    end

    task = Tasks.get_task!(id)
    {:ok, _task} = Tasks.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end

  def task_report(conn, _params) do
    if (!conn.assigns[:current_user]) do
      conn
      |> put_flash(:error, "You need to be logged in to generate a task report")
      |> redirect(to: Routes.user_path(conn, :index))
      |> halt
    end

    tasks = Tasks.task_report(conn.assigns[:current_user])
    render(conn, "index.html", tasks: tasks)
  end
end

hw07/lib/hw07_web/views/task_view.ex
defmodule Hw07Web.TaskView do
  use Hw07Web, :view
end

hw07/lib/hw07_web/templates/task/edit.html.eex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

hw07/lib/hw07_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

    <div "form-group">
      <%= label f, :title %>
      <%= text_input f, :title, class: "form-control" %>
      <%= error_tag f, :title %>
    </div>

    <div "form-group">
      <%= label f, :desc %>
      <%= textarea f, :desc, class: "form-control" %>

      <%= error_tag f, :desc %>
    </div>

    <div "form-group">
      <%= label f, :completed %>
      <%= checkbox f, :completed, class: "form-control" %>
      <%= error_tag f, :completed %>
    </div>

    <div "form-group">
      <%= label f, :user_id %>
      <%= select f, :user_id, @users, class: "form-control" %>
      <%= error_tag f, :user_id %>
    </div>
  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

hw07/lib/hw07_web/templates/task/index.html.eex
<h1>Tasks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Completed</th>
      <th>User Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.desc %></td>
      <td><%= task.completed %></td>
      <td><%= task.user.email %></td>

      <td>
        <%= link "Details", to: Routes.task_path(@conn, :show, task), class: "btn btn-secondary" %>
        <%= if @current_user && task.user.manager_id == @current_user.id do %>
          <%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-info" %>
          <%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: Routes.task_path(@conn, :new), class: "btn btn-primary" %></span>

hw07/lib/hw07_web/templates/task/new.html.eex
<h1>New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

hw07/lib/hw07_web/templates/task/show.html.eex
<div class="row">

    <div class="col-6">
        <h1>Show Task</h1>
        <ul>

          <li>
            <strong>Title:</strong>
            <%= @task.title %>
          </li>

          <li>
            <strong>Desc:</strong>
            <%= @task.desc %>
          </li>

          <li>
            <strong>Completed:</strong>
            <%= @task.completed %>
          </li>
        </ul>

        <span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task), class: "btn btn-secondary" %></span>
        <span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-info" %></span>

        <%= form_for @changeset, Routes.time_block_path(@conn, :create), fn f -> %>
              <%= if @changeset.action do %>
                <div class="alert alert-danger">
                  <p>Oops, something went wrong! Please check the errors below.</p>
                </div>
              <% end %>
            <div "form-group">
              <%= label f, :start_time %>
              <%= text_input f, :start_time, class: "form-control" %>
              <%= error_tag f, :start_time %>
            </div>
            <div "form-group">
              <%= label f, :end_time %>
              <%= text_input f, :end_time, class: "form-control" %>
              <%= error_tag f, :end_time %>
            </div>
            <%= hidden_input f, :task_id, value: @task.id %>
          <div>
            <%= submit "Save", class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>

    <div class="col-6">
        <div class="row">
            <p id="time-display">Not currently working on this task</p>
        </div>
        <div class="row">
            <button id="start-working-button"
                class="btn btn-primary">Start Working
            </button>
             <button id="stop-working-button"
                data-task-id="<%= @task.id %>"
                data-start-time=""
                class="btn btn-danger disabled">Stop Working
            </button>
        </div>

        <div id="time-blocks">
            <%= Enum.map @task.time_blocks, fn time_block ->  %>
                <div class="row">
                    <span>Started at: <%= DateTime.from_unix!(time_block.start_time, :millisecond) %></span>
                    <span>  Ended at:<%= DateTime.from_unix!(time_block.end_time, :millisecond) %></span>
                    <%= button "Delete", to: Routes.time_block_path(@conn, :delete, time_block), method: :delete, class: "btn btn-warning delete-button" %>
                </div>
            <% end %>
        </div>
    </div>
</div>